class ProfanityFilter {
  static const Set<String> _palabras = {
    // ── PUTA / PUTO ──────────────────────────────────────────────────────────
    'puta','puto','putas','putos',
    'putazo','putaza','putazos','putazas',
    'putote','putota','putotes','putotas',
    'putilla','putillo','putillas','putillos',
    'putita','putito','putitas','putitos',
    'puton','putona','putones','putonas',
    'putisimo','putisima','putisimos','putisimas',
    'putero','putera','puteros','puteras',
    'puteria','puterias','puti','puticlub','puticlubes',
    'reputa','reputo','reputas','reputos',
    'reputada','reputado','reputadas','reputados',
    'grandeputa','grandisimaputa','malaputa','malaputo',
    'hijadeputa','hijodeputa','hijasdeputa','hijosdeputa',
    'hijaeputa','hijoeputa','hijueputa','hijuepuetas','hijueputas',
    'putofacil','putazote','putazota',
    'puteo','puteas','putea','puteamos','puteais','putean',
    'putee','puteaste','putearon',
    'puteaba','puteabas','puteabamos','puteabais','puteaban',
    'puteare','putearas','puteara','putearemos','puteareis','putearan',
    'puteando','puteado','puteada','puteados','puteadas',
    'putearse','puteate','puteense','superputa','megaputa',

    // ── CHINGAR ──────────────────────────────────────────────────────────────
    'chingo','chingas','chinga','chingamos','chingais','chingan',
    'chingue','chingaste','chingaron','chingasteis',
    'chingaba','chingabas','chingabamos','chingabais','chingaban',
    'chingare','chingaras','chingara','chingaremos','chingareis','chingaran',
    'chinguen','chingues',
    'chingando','chingado','chingada','chingados','chingadas',
    'chingarse','chingate','chingaos','chinguense',
    'chingadera','chingaderas','chingadazo','chingadazos',
    'chingon','chingona','chingones','chingonas',
    'chingonada','chingonadas','chingonisimo','chingonisima',
    'rechingada','rechingado','rechingadas','rechingados',
    'chingaquedito','chingalamadre','chingalemadre',
    'pinchechingada','pinchechingado',
    'superchingon','megachingon','megachingona',
    'vetealachingada','alavechingada','nochingues','nochingen',
    'chingatetusmadre','chingatelo','chingatela',
    'chingadomadres','chingao',

    // ── CABRON ───────────────────────────────────────────────────────────────
    'cabron','cabrona','cabrones','cabronas',
    'cabronazo','cabronaza','cabronazos','cabronazas',
    'cabronada','cabronadas',
    'cabronzuelo','cabronzuela','cabronzuelos','cabronzuelas',
    'recabron','recabrona','recabrones','recabronas',
    'supercabron','megacabron',
    'cabronisimo','cabronisima','cabronisimos','cabronisimas',

    // ── PENDEJO ──────────────────────────────────────────────────────────────
    'pendejo','pendeja','pendejos','pendejas',
    'pendejada','pendejadas','pendejez','pendejeces',
    'pendejazo','pendejaza','pendejazos','pendejazas',
    'pendejote','pendejota','pendejotes','pendejotas',
    'pendejismo','pendejera','pendejeada','pendejeadas',
    'superpendejo','megapendejo',
    'pendejisimo','pendejisima','pendejisimos','pendejisimas',
    'pendejeo','pendejeas','pendejea','pendejeamos','pendejeais','pendejean',
    'pendejeaste','pendejearon',
    'pendejeando','pendejeado','pendejeada',

    // ── MIERDA / CAGAR ───────────────────────────────────────────────────────
    'mierda','mierdas','mierdon','mierdona','mierdones','mierdonas',
    'mierdazo','mierdaza','mierdazos','mierdazas',
    'mierdero','mierdera','mierderos','mierderas',
    'mierdoso','mierdosa','mierdosos','mierdosas',
    'mierdisimo','mierdisima',
    'cago','cagas','caga','cagamos','cagais','cagan',
    'cague','cagaste','cagaron','cagasteis',
    'cagaba','cagabas','cagabamos','cagabais','cagaban',
    'cagare','cagaras','cagara','cagaremos','cagareis','cagaran',
    'cagando','cagado','cagada','cagados','cagadas',
    'cagarse','cagate','caguense',
    'cagadera','cagadero','cagaderas','cagaderos',
    'caguetazo','caguetazos','caguetada','caguetas',
    'encagarse','encagado','encagada',
    'mear','meo','meas','mea','meamos','meais','mean',
    'mee','measte','mearon','meaba','meabas','meaban',
    'meando','meado','meada','meados','meadas',
    'mearse','meate','meense','meadero','meadera',
    'pedo','pedos','pedorro','pedorra','pedorros','pedorras',
    'pedorrada','pedorradas','pedorrera','pedorreando',
    'pedorrear','pedorreo',
    'caca','cacas','cacota','cacotas',
    'popo','popos',

    // ── VERGA ────────────────────────────────────────────────────────────────
    'verga','vergas','vergon','vergona','vergones','vergonas',
    'vergudo','verguda','vergudos','vergudas',
    'vergajazo','vergajazos','vergaza','vergazas',
    'verguero','verguera','vergote','vergotes',
    'alaverg','alaveriga',
    'chota','chotas','chotazo','chotazos',
    'chile','chiles',
    'picha','pichas','pichazo','pichazos','pichicata',
    'piringo','piringos','pirin',
    'falo','falos','falico','falica',
    'tranca','trancas',
    'pinga','pingas','pingudo','pinguda','pingon','pingona','pingones','pingonas',
    'bicho','bichos',
    'cipote','cipotes',

    // ── CULO / CULERO ────────────────────────────────────────────────────────
    'culo','culos','culito','culitos',
    'culona','culones','culonas',
    'culero','culera','culeros','culeras',
    'culerismo','culeria',
    'culazo','culaza','culazos','culazas',
    'culote','culotes','culota','culotas',
    'culon',
    'reculero','reculera','reculeros','reculeras',
    'culisimo','culisima','metaculo',
    'ojete','ojetes','ojeteada','ojeteado','ojeteadas','ojeteados',
    'ojeteando','ojetear',
    'culear','culeo','culeas','culea','culean',
    'culeaste','culearon','culeaba','culeabas','culeaban',
    'culeando','culeado','culeada','culeados','culeadas',
    'culiaos','culiada','culiado','culiao',

    // ── COÑO / CONCHA / PANOCHA ──────────────────────────────────────────────
    'cono','conos','concha','conchas',
    'conchuda','conchudo','conchudas','conchudos','conchudez',
    'panocha','panochas','panochon','panochona','panochones','panocheras',
    'chocho','chochos','chochada','chochadas',
    'chucha','chuchas','chucheta','chuchetas',
    'raja','rajas','rajada','rajadas',
    'chancha','chanchas',
    'papaya','papayas',

    // ── JOTO / MARICON ───────────────────────────────────────────────────────
    'joto','jota','jotos','jotas',
    'joton','jotona','jotones','jotonas',
    'jotear','joteado','joteada','joteando','jotera',
    'maricon','maricona','maricones','mariconas',
    'marica','maricas','maricada','maricadas',
    'mariconsillo','mariconsilla',
    'trolo','trolos','trola','trolas',
    'coliza','colizas',
    'cochon','cochona','cochones','cochonas',
    'pajaro','pajaros',

    // ── MAMADA / MAMON ───────────────────────────────────────────────────────
    'mamada','mamadas','mamon','mamona','mamones','mamonas',
    'mamo','mamas','mama','mamamos','mamais','maman',
    'mame','mamaste','mamaron','mamasteis',
    'mamaba','mamabas','mamaban',
    'mamando','mamado','mamada','mamar','mamarse','mamate',
    'mamonsote','mamona',
    'mamahuevo','mamahuevos','mamaguebo','mamaguebos',
    'mamacallos','mamacallo','mamalona','mamalones',
    'mamador','mamadora','mamadores','mamadoras',

    // ── PINCHE ───────────────────────────────────────────────────────────────
    'pinche','pinches',
    'pinchada','pinchado','pinchadas','pinchados',
    'pinchisimo','pinchisima','pinchisimos','pinchisimas',
    'pinchependejo','pinchependeja',
    'pincheculo','pincheverga','pincheputa',
    'pinchecabron','pinchemierda',

    // ── NALGAS ───────────────────────────────────────────────────────────────
    'nalga','nalgas','nalgon','nalgona','nalgones','nalgonas',
    'nalgazo','nalgazos','nalgaza','nalgazas',
    'nalguear','nalgueo','nalgueado','nalgueada',
    'nalguitas','nalgota','nalgotas',

    // ── PITO / PIJA ──────────────────────────────────────────────────────────
    'pito','pitos','pija','pijas',
    'pijazo','pijazos','pijada','pijadas',
    'pijero','pijera','pijeros','pijeras',
    'piton','pitona','pitones','pitonas',
    'pitote','pitotes',

    // ── COGER ────────────────────────────────────────────────────────────────
    'cojo','coges','coge','cogemos','cogeis','cogen',
    'cogi','cogiste','cogio','cogimos','cogisteis','cogieron',
    'cogia','cogias','cogiamos','cogiais','cogian',
    'cogere','cogeras','cogera','cogeremos','cogereis','cogeran',
    'cogiendo','cogido','cogida','cogidos','cogidas',
    'cogerse','cogelon','cogelona','cogelones','cogelonas',
    'cogedera','cogederas',

    // ── CARAJO ───────────────────────────────────────────────────────────────
    'carajo','carajos','carajada','carajadas',
    'carajote','carajotes','carajito','carajitos',
    'carajisimo','vetealacarajo','alcarajo',

    // ── HUEVON / WEON ────────────────────────────────────────────────────────
    'huevon','huevona','huevones','huevonas',
    'weon','weona','weones','weonas',
    'wea','weas',
    'huevonada','huevonadas',
    'ahuevado','ahuevada','ahuevados','ahuevadas',
    'huevudisimo','huevudisima',

    // ── MADRES ───────────────────────────────────────────────────────────────
    'chingalamadre','chingalemadre','chingalamadres',
    'tuputamadre','tuputa','tuputisimamadre',
    'vetetuputamadre','quetemadres',
    'madrazo','madrazos','madraza','madrazas',
    'madreada','madreado','madreadas','madreados',
    'madreo','madreas','madrea','madreamos','madrean',
    'madreaste','madrearon','madreando',
    'putamadre','putasmadres','putisimamadre',

    // ── FOLLAR (España) ──────────────────────────────────────────────────────
    'follo','follas','folla','follamos','follais','follan',
    'folle','follaste','follo','follamos','follasteis','follaron',
    'follaba','follabas','follabamos','follaban',
    'follare','follaras','follara','follaremos','follaran',
    'follando','follado','follada','follados','folladas',
    'follarse','follatelo','follatela','folladera',

    // ── JODER ────────────────────────────────────────────────────────────────
    'jodo','jodes','jode','jodemos','jodeis','joden',
    'jodi','jodiste','jodio','jodimos','jodisteis','jodieron',
    'jodia','jodias','jodiamos','jodian',
    'jodere','joderas','jodera','joderemos','joderan',
    'jodiendo','jodido','jodida','jodidos','jodidas',
    'joderse','jodete','jodanse','jodeos',
    'jodedera','jodederas',

    // ── GARCHAR (Argentina) ──────────────────────────────────────────────────
    'garchar','garcho','garchas','garcha','garchan',
    'garchaste','garcharon',
    'garchando','garchado','garchada','garchados','garchadas',

    // ── PAJEAR ───────────────────────────────────────────────────────────────
    'paja','pajas','pajada','pajadas',
    'pajeo','pajeas','pajea','pajeamos','pajean',
    'pajeaste','pajearon','pajeando','pajeado','pajeada',
    'pajearse','pajero','pajera','pajeros','pajeras',
    'pajon','pajona','pajones','pajonas',

    // ── CHUPAR ───────────────────────────────────────────────────────────────
    'chupo','chupas','chupa','chupamos','chupais','chupan',
    'chupe','chupaste','chupo','chupamos','chupasteis','chuparon',
    'chupaba','chupabas','chupaban',
    'chupando','chupado','chupada','chupados','chupadas',
    'chupate','chupense','chupador','chupadora',
    'chupetear','chupeteo','chupeada','chupeadas',

    // ── LAMER ────────────────────────────────────────────────────────────────
    'lamo','lames','lame','lamemos','lamen',
    'lami','lamiste','lamio','lamieron',
    'lamia','lamias','lamian',
    'lamiendo','lamido','lamida','lamidos','lamidas',
    'lambida','lambidas','lambetazo',

    // ── REGIONAL COLOMBIANO ──────────────────────────────────────────────────
    'gonorrea','gonorreas',
    'hijueputa','hijueputas','hpta',
    'guevon','guevona','guevones','guevonas',
    'pirobo','piroba','pirobos','pirobas',
    'sapo','sapa','sapos','sapas',
    'lacra','lacras',
    'carechiimba','carepicha','careverga',
    'gamines',

    // ── REGIONAL ARGENTINO ───────────────────────────────────────────────────
    'boludo','boluda','boludos','boludas',
    'boludez','boludeces',
    'pelotudo','pelotuda','pelotudos','pelotudas',
    'pelotudez','pelotudeces',
    'forro','forra','forros','forras',
    'forrada','forrado','forradas','forrados',
    'ortiva','ortivas','ortivo','ortivos',
    'gil','giles','gilada','giladas',
    'conchatumadre','conchadetumare','conchadelamadre',
    'hdp',
    'turro','turra','turros','turras',
    'otario','otaria','otarios','otarias',
    'cagon','cagona','cagones','cagonas',
    'sorete','soretes','soreta','soretas',
    'mogolico','mogolica',
    'villero','villera','villeros','villeras',

    // ── REGIONAL VENEZOLANO ──────────────────────────────────────────────────
    'conoetumadre',
    'marico','maricos',
    'pajuo','pajua','pajuos','pajuas',
    'guevo','gueva','guevos','guevas',
    'arrecho','arrecha','arrechos','arrechas',
    'vergatario','vergataria',

    // ── REGIONAL CHILENO ─────────────────────────────────────────────────────
    'conchetumare','conchetumadre',
    'culiao','culiada','culiaos','culiadas',
    'pico','picos',
    'tula','tulas',

    // ── REGIONAL ESPAÑOL ─────────────────────────────────────────────────────
    'gilipollas','gilipolla','gilipollez','gilipolleces',
    'capullo','capullos','capulla','capullas',
    'hostia','hostias','hostiaza','hostiazas','hostiazo','hostiazos',
    'coño',
    'polla','pollas','pollazo','pollazos',
    'puñeta','puñetas',
    'subnormal','subnormales',
    'soplagaitas','soplagaita',
    'mecachis','cabroncete','cabroncetes',
    'mamón','mamona',

    // ── REGIONAL CENTROAMERICA / CARIBE ──────────────────────────────────────
    'chingaste',
    'hueco','huecos',
    'mamabicho','mamabichos',
    'comemierda','comemierdas',
    'singao','singada','singaos','singadas',
    'singo','singas','singa','singan',
    'singando','singado','singada',

    // ── INSULTOS GENERALES ESPAÑOL ───────────────────────────────────────────
    'idiota','idiotas','idiotez','idioteces',
    'imbecil','imbeciles','imbecilidad',
    'estupido','estupida','estupidos','estupidas','estupidez','estupideces',
    'inutil','inutiles','inutilidad',
    'tarado','tarada','tarados','taradas',
    'burro','burra','burros','burras',
    'asno','asna','asnos','asnas',
    'bobo','boba','bobos','bobas','bobada','bobadas','bobera',
    'tonto','tonta','tontos','tontas','tontada','tontadas','tonteria','tonterias',
    'baboso','babosa','babosos','babosas','babosada','babosadas',
    'mensa','menso','mensas','mensos',
    'bruto','bruta','brutos','brutas','brutez',
    'bestia','bestias',
    'desgraciado','desgraciada','desgraciados','desgraciadas',
    'bastardo','bastarda','bastardos','bastardas',
    'malnacido','malnacida','malnacidos','malnacidas',
    'sinverguenza','sinverguenzas',
    'rata','ratas',
    'traidor','traidora','traidores','traidoras',
    'mentiroso','mentirosa','mentirosos','mentirosas',
    'hipocrita','hipocritas',
    'cobarde','cobardes','cobardada','cobardadas',
    'gallina','gallinas',
    'asqueroso','asquerosa','asquerosos','asquerosas',
    'repugnante','repugnantes',
    'malparido','malparida','malparidos','malparidas',
    'cerdo','cerda','cerdos','cerdas',
    'puerco','puerca','puercos','puercas',
    'cochino','cochina','cochinos','cochinas',
    'marrano','marrana','marranos','marranas',
    'chancho','chancha','chanchos','chanchas',
    'guarro','guarra','guarros','guarras',
    'zoquete','zoquetes',
    'patan','patanes',
    'maleducado','maleducada','maleducados','maleducadas',
    'grosero','grosera','groseros','groseras',
    'soez','soeces',
    'ordinario','ordinaria','ordinarios','ordinarias',
    'vulgar','vulgares','vulgaridad',
    'naco','naca','nacos','nacas','nacada','nacadas',
    'hocicon','hocicona','hocicones','hociconas',
    'chismoso','chismosa','chismosos','chismosas',
    'mamerto','mamerta','mamertos','mamertas',
    'gandalla','gandallas',
    'lacra',

    // ── SEXUAL / ANATOMIA EXTRA ───────────────────────────────────────────────
    'pornografia','porno','pornos','pornografico','pornografica',
    'orgasmo','orgasmos',
    'eyacular','eyaculacion','eyaculaciones',
    'masturbacion','masturbarse','masturbar','masturbandose',
    'semen','esperma','corrida','corridas',
    'felacion','felaciones',
    'cunnilingus','sodomia','sodomizar',
    'penetracion','penetraciones',
    'ereccion','erecciones',
    'excitacion',
    'prostituta','prostitutas','prostituto','prostitutos',
    'prostitucion',
    'putero','puteros','putera','puteras',
    'burdel','burdeles',
    'fichera','ficheras',
    'striper','stripper','strippers',
    'striptease','pornstar','pornstars',
    'camgirl','camboy','hentai',
    'voyeur','voyerismo',
    'fetichismo',
    'sadomasoquismo','sadismo','masoquismo',
    'bondage',
    'dildo','consolador','consoladores',
    'vibrador','vibradores',

    // ── DROGAS ───────────────────────────────────────────────────────────────
    'mota','motas',
    'marihuana','marijuana','mariguana','cannabis','ganja',
    'porro','porros',
    'toque','toques','grifa','grifas',
    'hierba','yerba',
    'cocaina','perico','talco','nieve',
    'raya','rayas','pase','pases',
    'cristal','hielo','meta','meth',
    'heroina','chiva','chivas',
    'crack','piedra',
    'activo','mona','thinner',
    'drogadicto','drogadicta','drogadictos','drogadictas',
    'drogado','drogada','drogados','drogadas',
    'tecato','tecata','tecatos','tecatas',
    'adicto','adicta','adictos','adictas',
    'narco','narcos','narcotraficante','narcotraficantes',
    'dealer','dealers','camello',
    'jalando','snorteando',
    'intoxicado','intoxicada',
    'viaje',
    'acido','acidos',
    'extasis','mdma',
    'ketamina','keta',

    // ── INSULTOS RACIALES / ETNICOS ───────────────────────────────────────────
    'prieto','prieta','prietos','prietas',
    'indio','india','indios','indias',
    'indito','indita',
    'gringo','gringa','gringos','gringas',
    'gabacho','gabacha','gabachos','gabachas',
    'pocho','pocha','pochos','pochas',
    'sudaca','sudacas',
    'beaner','beaners',
    'wetback','wetbacks',
    'spic','spics','spick','spicks',
    'mojado','mojada','mojados','mojadas',
    'mugroso','mugrosa','mugrosos','mugrosas',

    // ── ENGLISH: FUCK ────────────────────────────────────────────────────────
    'fuck','fucker','fuckers','fucking','fucked','fucks','fuckin',
    'motherfucker','motherfuckers','motherfuckin','motherfucking',
    'fuckup','fuckups','fuckhead','fuckheads',
    'clusterfuck','mindfuck','buttfuck','assfuck','facefuck',
    'fucktard','fucktards','fuckwit','fuckwits',
    'fuckface','fuckfaces','fuckboy','fuckboys','fuckgirl',
    'fucknugget','fucknuggets',
    'fookin','feckin','feck',
    'effing','effed',
    'wtaf',

    // ── ENGLISH: SHIT ────────────────────────────────────────────────────────
    'shit','shits','bullshit','bullshits',
    'shitty','shithead','shitheads',
    'shitstorm','shitshow','shithole','shitholes',
    'horseshit','dogshit','batshit','dipshit','dipshits',
    'apeshit','chickenshit','jackshit',
    'shitbag','shitbags','shitbird','shitbirds',
    'shitbrains','shitfaced',
    'shitgibbon','shitgibbons',
    'shitkicker','shitless','shitlist','shitlord',
    'shitpost','shitposts','shitposting',
    'shitstain','shitstains',

    // ── ENGLISH: BITCH ───────────────────────────────────────────────────────
    'bitch','bitches','bitchy','sobitch','sonofabitch','sonofabitches',
    'bitchass','bitchface','bitching','bitched',
    'bitchin','bitchiness',

    // ── ENGLISH: ASS ─────────────────────────────────────────────────────────
    'asshole','assholes','ass','asses',
    'assface','assfaces','asshat','asshats',
    'asskisser','asskissers',
    'assclown','assclowns','asswipe','asswipes',
    'assbag','assbags','asscheeks','asscrack',
    'assfucker',
    'smartass','smartasses','jackass','jackasses',
    'dumbass','dumbasses','fatass','fatasses',
    'lardass','badass','badasses',

    // ── ENGLISH: BASTARD / CUNT ───────────────────────────────────────────────
    'bastard','bastards',
    'cunt','cunts','cunty','cuntface','cunthead',
    'twatwaffle','twatface',

    // ── ENGLISH: COCK / DICK ──────────────────────────────────────────────────
    'cock','cocks','cocksucker','cocksuckers','cocksucking',
    'cockhead','cockheads','cockblock','cockblocks','cockblocking',
    'cockup','cockups','cocknose',
    'dick','dicks','dickhead','dickheads',
    'dickface','dickfaces','dickwad','dickwads',
    'dickweed','dickweeds','dickish',
    'dickbag','dickbags','dicknose','dickweasel','dickhole',

    // ── ENGLISH: PUSSY / WHORE / SLUT ─────────────────────────────────────────
    'pussy','pussies','pussyass','pussywhipped',
    'whore','whores','whoring','whorish',
    'whorebag','whorebags','whorehouse','whorehouses',
    'manwhore','camwhore','whoremonger',
    'slut','sluts','slutty','sluttiness',
    'slutbag','slutbags',
    'thot','thots',
    'hoe','hoes',
    'skank','skanks','skanky',
    'tramp','tramps',

    // ── ENGLISH: RACIAL SLURS ─────────────────────────────────────────────────
    'nigger','nigga','niggas','niggah','niggaz','niggers',
    'coon','coons','jigaboo','jigaboos',
    'sambo','sambos','darkie','darkies',
    'porchmonkey',
    'kike','kikes',
    'chink','chinks',
    'gook','gooks','slope','slopes',
    'towelhead','towelheads','raghead','ragheads',
    'sandnigger','sandniggers',
    'cracker','crackers',
    'honky','honkies','honkeys',
    'redskin','redskins',
    'injun','injuns',
    'nip','nips',
    'jap','japs',
    'spook',

    // ── ENGLISH: HOMOFOBIC ───────────────────────────────────────────────────
    'faggot','faggots','fag','fags','fagging',
    'dyke','dykes',
    'homo','homos',
    'fruitcake',

    // ── ENGLISH: TWAT / WANKER / MISC ────────────────────────────────────────
    'twat','twats',
    'wanker','wankers','wanking','wanked','wank','wanks',
    'tosser','tossers','tossing',
    'bugger','buggers','buggering','buggered',
    'bollocks','bollock',
    'knob','knobs','knobhead','knobheads',
    'pillock','pillocks','plonker','plonkers',
    'bellend','bellends',
    'minger','mingers',
    'prick','pricks','prickhead',
    'numbnuts','numskull','numbskull',
    'crackhead','crackheads',
    'junkie','junkies',
    'scumbag','scumbags',
    'douchebag','douchebags','douche','douches','douchey',
    'toolbag','toolbags',
    'loser','losers',
    'pervert','perverts','perv','pervs',
    'sicko','sickos',
    'retard','retarded','retards',
    'idiot','idiots','moron','morons',
    'imbecile','imbeciles',
    'jerk','jerks','jerkoff','jerkoffs',
    'pissoff','pissed',
    'damn','damned','damnit','goddamn','goddamned','goddamnit',
    'crap','crappy','craps',
    'screw_you',

    // ── FORMAS CONDICIONALES VERBOS PRINCIPALES ───────────────────────────────
    'chingaria','chingarias','chingariamos','chingarian',
    'cagaria','cagarias','cagariamos','cagarian',
    'mearia','mearias','meariamos','mearian',
    'cogeria','cogerias','cogeriamos','cogerian',
    'follaria','follarias','follariamos','follarian',
    'joderia','joderias','joderiamos','joderian',
    'garcharia','garcharias','garchariamos','garcharian',
    'culearia','culearias','culeariamos','culearian',
    'pajearia','pajearias','pajeariamos','pajearian',
    'chuparia','chuparias','chupariamos','chuparian',
    'mamaria','mamarias','mamariamos','mamarian',
    'putearia','putearias','puteariamos','putearian',
    'singaria','singarias','singariamos','singarian',
    'lameria','lamerias','lameriamos','lamerian',
    'madrearia','madrearias','madreariamos','madrearian',

    // ── SUBJUNTIVO IMPERFECTO -SE VERBOS PRINCIPALES ──────────────────────────
    'chingase','chingases','chingasemos','chingasen',
    'cagase','cagases','cagasemos','cagasen',
    'measen','meases','mease',
    'cogiese','cogieses','cogiesemos','cogiesen',
    'follase','follases','follasen',
    'jodiese','jodieses','jodiesemos','jodiesen',
    'garchase','garchases','garchansen',
    'culedse','culeases','culeasen',
    'pajease','pajeases','pajeasen',
    'chupase','chupases','chupasen',
    'mamase','mamases','mamasen',
    'putease','puteases','puteasen',
    'singase','singases','singasen',
    'lamase','lamases','lamasen',

    // ── CONJUGACIONES ADICIONALES CHINGAR ────────────────────────────────────
    'nochingues','nochingue','nochinguemos','nochingueis','nochinguen',
    'chingaras','chingara','chingaramos','chingarais',
    'chingue','chingues','chinguemos','chingueis',
    'achingarse','achingado','achingada',

    // ── CONJUGACIONES ADICIONALES CAGAR ──────────────────────────────────────
    'nocagues','nocague','nocaguemos','nocagueis','nocaguen',
    'cague','cagues','caguemos','cagueis','caguen',
    'cagara','cagaras','cagaramos','cagarais',
    'encago','encagas','encaga','encagan',
    'encagarse','encagate',

    // ── CONJUGACIONES ADICIONALES COGER ──────────────────────────────────────
    'coja','cojas','cojamos','cojais','cojan',
    'cogiera','cogieras','cogieramos','cogieran',
    'nocoja','nocojas','nocojan',

    // ── CONJUGACIONES ADICIONALES FOLLAR ─────────────────────────────────────
    'folle','folles','follemos','folleis','follen',
    'follara','follaras','follaramos','follarais',
    'nofolles','nofollen','nofolleis',

    // ── CONJUGACIONES ADICIONALES JODER ──────────────────────────────────────
    'joda','jodas','jodamos','jodais','jodan',
    'jodiera','jodieras','jodieramos','jodieran',
    'nojodas','nojoda','nojodan',

    // ── CONJUGACIONES ADICIONALES MAMAR ──────────────────────────────────────
    'mame','mames','mamemos','mameis','mamen',
    'mamara','mamaras','mamaramos','mamarain',
    'nomames','nomame','nomamen',

    // ── CONJUGACIONES ADICIONALES CHUPAR ─────────────────────────────────────
    'chupe','chupes','chupemos','chupeis','chupen',
    'chupara','chuparas','chuparamos','chuparain',
    'nochupes','nochupe','nochupen',

    // ── IMPERATIVOS NEGATIVOS ────────────────────────────────────────────────
    'nofolles','nofollen',
    'nocogeras','nocoja',
    'nojodas','nojoda',
    'nomameis','nomamen',

    // ── MEXICO: SLANG ADICIONAL ───────────────────────────────────────────────
    'buey','bueyes','guey','gueys','güey','güeys',
    'wey','weys',
    'culero','culera',
    'menso','mensa',
    'baboso','babosa',
    'tarugo','taruga','tarugos','tarugas',
    'ahuevo','ahuevos',
    'chale','chales',
    'orale',
    'chiflado','chiflada','chiflados','chifladas',
    'payaso','payasa','payasos','payasas',
    'fresa','fresas','fresero','fresera',
    'mamila','mamilas',
    'charolastra',
    'metiche','metiches',
    'chillón','chillona','chillones','chillonas',
    'berrinchudo','berrinchuda','berrinchudos','berrinchudas',
    'berrinche','berrinches',
    'lloron','llorona','llorones','lloronas',
    'rajón','rajona','rajones','rajonas',
    'lagartón','lagartona','lagartonas',
    'vivales','vivo','viva',
    'codo','coda','codos','codas',
    'garrón','garrona','garrones','garronas',
    'pato','pata','patos','patas',
    'tarado','tarada',
    'encuerado','encuerada','encuerados','encueradas',
    'calacas',
    'mequetrefe','mequetrefes',
    'pelele','peleles',
    'zángano','zángana','zánganos','zánganas',
    'maldoso','maldosa','maldosos','maldosas',
    'mamagallo','mamagallos',
    'mula','mulas',
    'maldito','maldita','malditos','malditas',
    'fregado','fregada','fregados','fregadas',
    'fregas','fregon','fregona',
    'jodido','jodida',
    'pato','patas',
    'mojon','mojones',
    'mojona','mojonas',

    // ── MEXICO: JERGA CALLEJERA ───────────────────────────────────────────────
    'ojete','ojetes',
    'piruja','pirujas','pirujero','pirujera',
    'tepiteño','tepiteña',
    'naco','naca',
    'naquez','nacada',
    'chalchihuites',
    'esquincle','esquincles',
    'guarura','guaruras',
    'gorrón','gorrona','gorrones','gorronas',
    'gorrear','gorreo','gorreado','gorreada',
    'tranza','tranzas',
    'trucha',
    'cholo','chola','cholos','cholas',
    'chaca','chacas',
    'bato','bata','batos','batas',
    'leva','levas',

    // ── PERU: INSULTOS REGIONALES ─────────────────────────────────────────────
    'concha','conchas',
    'conchatumadre','conchatumare',
    'cojudo','cojuda','cojudos','cojudas',
    'cojudez','cojudeces',
    'manada','manadas',
    'awebo','aweba','awevos',
    'aweonao','aweonada',
    'mamalon','mamalona',
    'pituco','pituca','pitucos','pitucias',
    'resentido','resentida',
    'cagon','cagona',
    'ladrillo','ladrillos',
    'huevero','huevera',
    'idioto','idiota',
    'sopla','soplas',
    'soplapitas','soplapita',
    'chauchero','chauchera',
    'aniña','aniñado','aniñada',
    'huachaferia','huachafero','huachaferia',
    'zambo','zamba','zambos','zambas',

    // ── PUERTO RICO / CARIBE: INSULTOS ────────────────────────────────────────
    'cabrón','cabrona',
    'mamaguebo','mamaguebos',
    'mamabicho','mamabichos',
    'pato','pata',
    'cotorra','cotorras',
    'nene','nena',
    'jibaro','jibara','jibaros','jibaras',
    'jorobado','jorobada','jorobados','jorobadas',
    'coño','coños',
    'puñeta','puñetas',
    'pendejo','pendeja',
    'wepa',
    'bienmesabe',
    'carajete','carajetes',
    'carajonazo',

    // ── DOMINICANA: INSULTOS ──────────────────────────────────────────────────
    'cepillo','cepillos',
    'tiguere','tigueres',
    'diablo','diablos',
    'maleante','maleantes',
    'puta','putas',
    'degenerao','degenerada','degenerados','degeneradas',
    'bruto','bruta',
    'maldita','maldito',
    'sinverguenza',
    'cabron',
    'comemierda',
    'cagadera',
    'nojoda',
    'coñazo','coñazos',
    'tiguere',

    // ── CUBA: INSULTOS ────────────────────────────────────────────────────────
    'asere','aseres',
    'bicho','bichos',
    'singao','singados',
    'mierda',
    'cabron',
    'comemierda','comemierdas',
    'sociolismo',
    'pincha','pinchas',
    'mosquita',
    'mogollon','mogollo',
    'tremendo','tremenda',
    'pendejo',

    // ── BOLIVIA / ECUADOR / PARAGUAY ─────────────────────────────────────────
    'poto','potos',
    'potada','potadas',
    'culo',
    'concha',
    'cojo','coja',
    'yegua','yeguas',
    'sopla','soplas',
    'soplaverga','soplavergasos',
    'mamon',
    'boludo',
    'pelotudo',
    'pendejo',
    'imbecil',
    'bruto',
    'idiota',
    'cagada','cagadas',
    'huevon','huevona',
    'huevonada',

    // ── URUGUAY: INSULTOS ─────────────────────────────────────────────────────
    'pelotudo','pelotuda',
    'boludo','boluda',
    'forro','forra',
    'gil','gila',
    'cagon','cagona',
    'mogolico','mogolica',
    'sorete',
    'turro','turra',
    'gil',
    'pajero','pajera',
    'caretazo','caretaza',
    'gaston','gastona',

    // ── PANAMA / HONDURAS / NICARAGUA ────────────────────────────────────────
    'culeado','culeada','culeados','culeadas',
    'chuco','chuca','chucos','chucas',
    'vergazo','vergazos',
    'vergajoso','vergajosa',
    'culeco','culeca',
    'sapo','sapa',
    'chuco','chuca',
    'jodido','jodida',
    'puñetero','puñetera',
    'rabo','rabos',
    'picho','picha',
    'bolo','bola','bolos','bolas',

    // ── Guatemala / EL SALVADOR ───────────────────────────────────────────────
    'culero','culera',
    'maje','majes',
    'chuchumeco','chuchumeca',
    'chinchilín',
    'puta',
    'verga',
    'hueco','hueca',
    'chucho','chucha',
    'baboso','babosa',
    'chele','cheles',
    'bolo','bola',
    'culio','culia',

    // ── INSULTOS DE APARIENCIA/FISICOS ADICIONALES ───────────────────────────
    'gordo','gorda','gordos','gordas',
    'gordito','gordita','gorditos','gorditas',
    'gordiflón','gordiflona',
    'flacucho','flacucha',
    'feo','fea','feos','feas',
    'feote','feota','feotes','feotas',
    'feuchon','feuchona',
    'horroroso','horrorosa',
    'espantoso','espantosa',
    'narigon','narigona',
    'narizon','narizota',
    'orejudo','orejuda',
    'orejón','orejona',
    'cabezón','cabezona',
    'cabezota','cabezotas',
    'calvo','calva','calvos','calvas',
    'calvete','calvetes',
    'pelon','pelona','pelones','pelonas',
    'bajito','bajita',
    'chaparro','chaparra',
    'enano','enana','enanos','enanas',
    'patizambo','patizamba',
    'zambo','zamba',
    'chistoso','chistosa',
    'bizco','bizca','bizcos','bizcas',
    'tuerto','tuerta','tuertos','tuertas',
    'sordo','sorda','sordos','sordas',
    'tartamudo','tartamuda',
    'cojo','coja','cojos','cojas',
    'manco','manca','mancos','mancas',
    'renco','renca','rencos','rencas',
    'deforme','deformes',
    'costuron','costurona',
    'cicatrizado','cicatrizada',

    // ── INSULTOS DE INTELIGENCIA ADICIONALES ─────────────────────────────────
    'tonto','tonta',
    'idiota','idiotas',
    'imbecil','imbeciles',
    'estupido','estupida',
    'menso','mensa',
    'bobo','boba',
    'burro','burra',
    'asno','asna',
    'tarado','tarada',
    'lerdo','lerda',
    'torpe','torpes',
    'inutil','inutiles',
    'negado','negada',
    'zote','zotes',
    'zoquete','zoquetes',
    'zopenco','zopenca',
    'tontivano','tontivana',
    'pazguato','pazguata','pazguatos','pazguatas',
    'pasmado','pasmada','pasmados','pasmadas',
    'badulaque','badulaques',
    'alcornoque','alcornoques',
    'bodoque','bodoques',
    'nulo','nula','nulos','nulas',
    'paniaguado','paniaguada',
    'insensato','insensata',
    'fatuo','fatua',
    'necio','necia','necios','necias',
    'obtuso','obtusa','obtusos','obtusas',
    'obtuso',
    'lento','lenta','lentos','lentas',
    'torpe',

    // ── INSULTOS MORALES / CARACTER ───────────────────────────────────────────
    'hipocrita','hipocritas',
    'traidor','traidora','traidores','traidoras',
    'mentiroso','mentirosa',
    'cobarde','cobardes',
    'mezquino','mezquina','mezquinos','mezquinas',
    'ruin','ruines',
    'miserable','miserables',
    'despreciable','despreciables',
    'abyecto','abyecta',
    'rastrero','rastrera',
    'rastrero',
    'canalla','canallas',
    'bribón','bribona','bribones','bribonas',
    'pillos','pilla','pillas',
    'granuja','granujas',
    'rufián','rufiana','rufianes','rufianas',
    'delincuente','delincuentes',
    'criminal','criminales',
    'maleante','maleantes',
    'malhechor','malhechora',
    'marginal','marginales',
    'mala_persona',
    'egoista','egoistas',
    'aprovechado','aprovechada',
    'oportunista','oportunistas',
    'vividor','vividora',
    'gorrón','gorrona',
    'parásito','parásita','parásitos','parásitas',
    'sanguijuela','sanguijuelas',
    'chupasangre','chupasangres',
    'corrupto','corrupta','corruptos','corruptas',
    'sobornador','sobornadora',
    'taimado','taimada','taimados','taimadas',
    'ladino','ladina','ladinos','ladinas',
    'artero','artera','arteros','arteras',
    'embustero','embustera',
    'farsante','farsantes',
    'charlatán','charlatana',
    'impostor','impostora','impostores','impostoras',
    'simulador','simuladora',
    'fanfarrón','fanfarrona','fanfarrones','fanfarronas',
    'engreído','engreída',
    'petulante','petulantes',
    'prepotente','prepotentes',
    'altanero','altanera',
    'soberbio','soberbia',
    'arrogante','arrogantes',
    'vanidoso','vanidosa',
    'presumido','presumida',
    'pagado','pagada',

    // ── INSULTOS ANIMALES ─────────────────────────────────────────────────────
    'perro','perra','perros','perras',
    'perrote','perrota',
    'perrazo','perraza',
    'perrada','perradas',
    'puerco','puerca',
    'cochino','cochina',
    'marrano','marrana',
    'chancho','chancha',
    'cerdo','cerda',
    'cerdazo','cerdaza',
    'burro','burra',
    'asno','asna',
    'mula','mulas',
    'vaca','vacas',
    'vacona','vaconas',
    'vaquilla','vaquillas',
    'ternera','terneras',
    'yegua','yeguas',
    'yeguazo','yeguaza',
    'bestia','bestias',
    'animal','animales',
    'bruto','bruta',
    'bestión','bestiona',
    'buitre','buitres',
    'zorro','zorra','zorros','zorras',
    'zorrazo','zorraza',
    'zorrona','zorronas',
    'hiena','hienas',
    'víbora','víboras',
    'sierpe','sierpes',
    'culebra','culebras',
    'serpiente','serpientes',
    'araña','arañas',
    'garrapata','garrapatas',
    'piojo','piojos',
    'ladilla','ladillas',
    'pulga','pulgas',
    'chinche','chinches',
    'cucaracha','cucarachas',
    'sabandija','sabandijas',
    'alimaña','alimañas',
    'chacal','chacales',
    'buitre',
    'cocodrilo','cocodrilos',
    'crocodilo','crocodilos',
    'hipopótamo','hipopótamos',

    // ── SEXUAL: INSULTOS Y ACTOS ADICIONALES ─────────────────────────────────
    'golfa','golfas','golfante','golfantes',
    'ramera','rameras',
    'meretriza','meretrizas',
    'meretriz','meretrices',
    'hetaira','hetairas',
    'cortesana','cortesanas',
    'querida','queridas',
    'mantenida','mantenidas',
    'ligue','ligues',
    'lujuria','lujurias',
    'lascivia','lascivias',
    'libidinoso','libidinosa',
    'lubrico','lubrica',
    'salaz','salaces',
    'caliente','calientes',
    'calenton','calentura',
    'rijoso','rijosa','rijosos','rijosas',
    'cachondo','cachonda','cachondos','cachondas',
    'calentorro','calentura',
    'morboso','morbosa','morbosos','morbosas',
    'pervertido','pervertida','pervertidos','pervertidas',
    'degenerado','degenerada',
    'vicioso','viciosa',
    'depravado','depravada',
    'promiscuo','promiscua',
    'libertino','libertina',
    'desvergonzado','desvergonzada',
    'desvergonzón','desvergonzona',
    'destapado','destapada',
    'exhibicionista','exhibicionistas',
    'ninfomana','ninfomanas',
    'ninfomaníaco','ninfomaniaca',
    'satíriaco','satirica',
    'casanova','casanovas',
    'donjuan','donjuanes',
    'ligón','ligona','ligones','ligonas',
    'mujeriego','mujeriegas',
    'putañero','putañera',
    'puterío','puterías',
    'prostitución',
    'lupanar','lupanares',
    'burdel',
    'prostíbulo','prostíbulos',
    'mancebía','mancebías',
    'antro','antros',
    'tugurio','tugurios',

    // ── DROGAS: MAS TERMINOS ──────────────────────────────────────────────────
    'porro','porros',
    'canuto','canutos',
    'petardo','petardos',
    'churro','churros',
    'brujula','brujulas',
    'truco','trucos',
    'chino','chinos',
    'revirado','revirada',
    'pasado','pasada',
    'trabado','trabada',
    'grifo','grifa','grifos','grifas',
    'fumeta','fumetas',
    'fumado','fumada',
    'pirado','pirada','pirados','piradas',
    'colocado','colocada',
    'elevado','elevada',
    'colgado','colgada',
    'volado','volada',
    'loquete','loquetes',
    'mocoso','mocosa',
    'yonqui','yonquis',
    'heroinómano','heroinomana',
    'cocainómano','cocainomana',
    'morfinómano','morfinomana',
    'drogata','drogatas',
    'camello','camellos',
    'narquillo','narquilla',
    'traqueto','traqueta','traquetos','traquetas',
    'chirrete','chiretes',
    'chorro','chorra','chorros','chorras',
    'chiva','chivas',
    'bazuco','bazucos',
    'basuco','basucos',
    'jaco','jacos',
    'hachis','hachís',
    'costo','costos',
    'speed','speedball',
    'anfeta','anfetas',

    // ── ENGLISH: ADDITIONAL FUCK VARIANTS ────────────────────────────────────
    'fuckall','fuckwad','fuckwads',
    'fuckstick','fucksticks',
    'fuckhole','fuckholes',
    'fucklord','fucklords',
    'fuckpig','fuckpigs',
    'fuckweasel','fuckweasels',
    'fuckass','fuckasses',
    'fucknut','fucknuts',
    'fuckmouth','fuckmouths',
    'fucknob','fucknobs',
    'fucktwat','fucktwats',
    'fuckwagon','fuckwagons',
    'fuckbox','fuckboxes',
    'fuckstain','fuckstains',
    'fuckbag','fuckbags',
    'fuckrag','fucktags',
    'fucktrumpet','fucktrumpets',
    'fukker','fukkers',
    'fooker','fookers',
    'fugger','fuggers',
    'phuck','phucker','phuckers','phucking','phucked',
    'fuggin','fugly',
    'frigging','frigged',
    'fricken','fricking',
    'frickin',
    'friggin',

    // ── ENGLISH: SHIT VARIANTS ────────────────────────────────────────────────
    'sh1tty','sh1thead',
    'shithole','shitholes',
    'shitbrick','shitbricks',
    'shitbucket','shitbuckets',
    'shitcock','shitcocks',
    'shitpants','shitpantser',
    'shitmouth','shitmouths',
    'shitbrain','shitbrains',
    'shiteater','shiteaters',
    'shitlicker','shitlickers',
    'shitnugget','shitnuggets',
    'shitpile','shitpiles',
    'shitsmear','shitsmears',
    'shitspray','shitsprays',
    'shitsack','shitsacks',
    'shitfling','shitflinger','shitflingers',
    'total_bullshit','utter_bullshit',
    'crapola','crappe','crappy',
    'craphead','crapheads',
    'craphole','crapholes',
    'crapper','crappers',
    'crapfest','crapfests',
    'crapstorm','crapstorms',
    'crapcake','crapcakes',

    // ── ENGLISH: ASS VARIANTS ─────────────────────────────────────────────────
    'a$$hole','a$$',
    'arse','arsehole','arseholes','arses',
    'arseclown','arseclowns',
    'arsewipe','arsewipes',
    'arsehat','arsehats',
    'butthole','buttholes',
    'buttface','buttfaces',
    'butthead','buttheads',
    'buttmunch','buttmuncher',
    'buttnugget','buttnuggets',
    'buttpig','buttpigs',
    'buttstain','buttstains',
    'buttwipe','buttwipes',
    'butt','butts',
    'assbite','assbites',
    'assnugget','assnuggets',
    'assmonger','assmongers',
    'assmaggot','assmaggots',
    'asspirate','asspirates',
    'halfassed','halfasses',
    'assrash','assrashes',

    // ── ENGLISH: DICK/COCK VARIANTS ───────────────────────────────────────────
    'dickhole','dickholes',
    'dicknugget','dicknuggets',
    'dickrot','dickrots',
    'dickbrain','dickbrains',
    'dickeater','dickeaters',
    'dicklet','dicklets',
    'dickmonger','dickmongers',
    'dicksuck','dicksuckers',
    'dickrash','dickrashes',
    'cocksmoker','cocksmokers',
    'cockjockey','cockjockeys',
    'cockwaffle','cockwaffles',
    'cockwomble','cockwombles',
    'cockmonster','cockmonsters',
    'cockmaster','cockmasters',
    'cocknob','cocknobs',
    'cockeye','cockeyes',
    'cocksmith','cocksmiths',
    'cockspank',

    // ── ENGLISH: BITCH/WHORE VARIANTS ────────────────────────────────────────
    'bitchcakes','dumbbitches',
    'ratchet','ratchets',
    'smeghead','smegheads',
    'skankbag','skankbags',
    'skankhoe','skankhoes',
    'whoreish',
    'prostie','prosties',
    'skeeze','skeezers','skeezer',
    'skeeze','skeezy',
    'floozy','floozies',
    'hoebag','hoebags',
    'hobo',
    'hoochie','hoochies',
    'sexpot','sexpots',
    'sexworker','sexworkers',
    'strumpet','strumpets',
    'harlot','harlots',
    'jezebel','jezebels',
    'vamp','vamps',
    'vixen','vixens',
    'coquette','coquettes',
    'succubus','succubi',

    // ── ENGLISH: IDIOT VARIANTS ───────────────────────────────────────────────
    'numpty','numpties',
    'walloper','wallopers',
    'bampot','bampots',
    'dobber','dobbers',
    'muppet','muppets',
    'divvy','divvies',
    'berk','berks',
    'berk',
    'prat','prats',
    'nob','nobs',
    'chav','chavs','chavvy',
    'pleb','plebs',
    'mong','mongs',
    'spaz','spazzes','spazzy',
    'gimp','gimps',
    'doorknob','doorknobs',
    'dingus','dinguses',
    'dingbat','dingbats',
    'dingdong','dingdongs',
    'meatball','meatballs',
    'clodhopper','clodhoppers',
    'klutz','klutzes',
    'doofus','doofuses',
    'oaf','oafs',
    'lout','louts',
    'lummox','lummoxes',
    'galoot','galoots',
    'bozo','bozos',
    'clown','clowns',
    'buffoon','buffoons',
    'clod','clods',
    'dunce','dunces',
    'simpleton','simpletons',
    'dullard','dullards',
    'dolt','dolts',
    'blockhead','blockheads',
    'bonehead','boneheads',
    'woodenhead','woodenheads',
    'mutton','muttons',
    'chump','chumps',
    'sucker','suckers',
    'sap','saps',
    'patsy','patsies',
    'shmuck','shmucks',
    'putz',

    // ── ENGLISH: RACISMO ADICIONAL ────────────────────────────────────────────
    'zipperhead','zipperheads',
    'yellowskin','yellowskins',
    'brownie','brownies',
    'mud',
    'coon',
    'sambo',
    'pickaninny','pickaninnies',
    'minstrel','minstrels',
    'mammy',
    'buckwheat',
    'ghetto','ghettoes',
    'thug','thugs',
    'gangbanger','gangbangers',
    'hood','hoods',
    'hoodrat','hoodrats',
    'redneck','rednecks',
    'hillbilly','hillbillies',
    'trailer_trash',
    'white_trash',
    'peckerwood','peckerwoods',
    'greaseball','greaseballs',
    'dago','dagos',
    'wop','wops',
    'kraut','krauts',
    'frog','frogs',
    'froggie','froggies',
    'limey','limeys',
    'pommy','pommies',
    'boong','boongs',
    'coon',

    // ── ENGLISH: MISC INSULTS ─────────────────────────────────────────────────
    'worthless','worthlessness',
    'useless','uselessness',
    'pathetic','pathetically',
    'lame','lamest',
    'garbage','garbages',
    'trash','trashes',
    'filth','filths',
    'vermin','vermins',
    'scum','scums',
    'lowlife','lowlifes',
    'degenerate','degenerates',
    'sleaze','sleazes','sleazy',
    'sleazebag','sleazebags',
    'slimeball','slimeballs',
    'slimebucket','slimebuckets',
    'dirtbag','dirtbags',
    'scuzzbag','scuzzbags',
    'ratfink','ratfinks',
    'weasel','weasels',
    'snake','snakes',
    'viper','vipers',
    'rat','rats',
    'stooge','stooges',
    'minion','minions',
    'shill','shills',
    'snitch','snitches',
    'narc','narcs',
    'sellout','sellouts',
    'turncoat','turncoats',
    'backstabber','backstabbers',
    'two_faced',
    'brownnoser','brownnoses',
    'asslicker','asslickers',
    'asskisser','asskissers',
    'sycophant','sycophants',
    'bootlicker','bootlickers',
    'toady','toadies',
    'lickspittle','lickspittles',
    'yes_man',
    'coward','cowards',
    'chicken','chickens',
    'wimp','wimps',
    'wuss','wusses',
    'pushover','pushovers',
    'doormat','doormats',
    'spineless','spinelessly',
    'milksop','milksops',
    'namby_pamby',
    'pissant','pissants',
    'shrimp','shrimps',
    'runt','runts',
    'turd','turds',
    'turdburger','turdburgers',
    'turdmuncher','turdmunchers',
    'dingwad','dingwads',
    'knucklehead','knuckleheads',
    'blockhead',
    'lamebrain','lamebrains',
    'harebrain','harebrains',
    'featherbrain','featherbrains',
    'scatterbrain','scatterbrains',
    'birdbrain','birdbrains',
    'peabrain','peabrains',

    // ── INTERNET / GAMING / SOCIAL MEDIA ──────────────────────────────────────
    'wtf','stfu','gtfo','fml','ffs','omfg',
    'sob','pos','mf','mfker',
    'kys','kms',
    'af','tf',
    'bs','bullsh',
    'foh','gtfoh',
    'smh',
    'noob','noobs','n00b','n00bs',
    'noobie','noobies',
    'scrub','scrubs',
    'trash','trashes',
    'git_gud',
    'salty','saltiness',
    'triggered',
    'troll','trolls','trolling','trolled',
    'toxic','toxicity',
    'hater','haters',
    'simp','simps','simping',
    'incel','incels',
    'virgin','virgins',
    'neckbeard','neckbeards',
    'manlet','manlets',
    'beta','betas',
    'cuck','cucks','cucked','cucking',
    'snowflake','snowflakes',
    'libtard','libtards',
    'retard',
    'ree','reee',
    'cancer','cancerous',
    'cringe','cringy',
    'npc','npcs',
    'boomer','boomers',
    'ok_boomer',
    'soyboy','soyboys',
    'numale','numales',

    // ── LEET SPEAK ───────────────────────────────────────────────────────────
    'fuk','fuq','fck',
    'sh1t',
    'b1tch',
    'a55','a55hole',
    'n1gger','n1gga',
    'c0ck','d1ck',
    'p0rn','p0rno',
    'ch1nga','ch1ngada',
    'v3rga',
    'put4','put0',
    'p3ndejo','p3ndeja',
    'c4bron',
    'h1jodeputa','h1jueputa',
    'f4ggot','f4g',
    'wh0re','s1ut',
    'm13rda','m1erda',
    'c4go','c4gar',
    'm4m4da','m4m0n',
    'v3rgaz0',
    'j0der','j0dio',
    'f0llar','f0llado',
    'c4bron4','c4br0n',
    'p1nche','p1nch3',
    'h1jo','h1jueputa',
    'p3rr4','p3rro',
    'c0n0','c0ñ0',
    'b4st4rd','b4stard',
    'st4pid','stup1d',
    'f00k','f00ker',
    'a$$','a55',
    'b1g_d1ck',
    'c0cks','d1cks',
    'p3nis','p3ne',
    'b1tch4ss',

    // ── CONJUGACIONES VERBOS SECUNDARIOS ─────────────────────────────────────
    // putear todos los tiempos
    'puteas','puteo','putean','puteamos','puteais',
    'putee','puteaste','puteo','putearon',
    'puteaba','puteabas','puteabamos','puteaban',
    'puteare','putearas','puteara','putearan',
    'putearia','putearias','putearian',
    'putee','putees','puteen',
    // culparse, zorronear, etc.
    'culparse','culpan','culpas',
    'zorronear','zorroneas','zorronea','zorroneamos','zorroneais','zorroneaban',
    'mariconear','mariconeas','mariconea','mariconeamos','mariconeaban',
    'mariconeando','mariconeado','mariconeada',
    'putilear','putileando','putileado','putileada',

    // ── VERBOS MALSONANTES ADICIONALES EN ESPAÑOL ──────────────────────────────
    // cabronear
    'cabroneo','cabroneas','cabronea','cabroneamos','cabroneain','cabronean',
    'cabroneaste','cabronearon','cabroneaba','cabroneabas','cabroneaban',
    'cabroneando','cabroneado','cabroneada',
    // pendejear
    'pendejeo','pendejeas','pendejea','pendejeamos','pendejean',
    'pendejeaste','pendejearon','pendejeaba','pendejeaban',
    'pendejeando',
    // mangonear
    'mangonear','mangoneando','mangoneado','mangoneada',
    'mangoneaste','mangonearon',
    // gargajear
    'gargajear','gargajeo','gargajeas','gargajeando','gargajeado',
    // chingaqueditar
    'chingaqueditar','chingaquedito',
    // hijueputear
    'hijueputear','hijueputeo','hijuepuetaste','hijueputeando',
    // pendejear variantes
    'pendejeo','pendejas',

    // ── GROSERÍAS RELIGIOSAS ───────────────────────────────────────────────────
    'mecagoendios','mecagoenlatina','mecagonlatina',
    'mecagoenlavirgen','mecagoenelmundo','mecagoensutumba',
    'mecagoentodo','mecagoentus',
    'mecagoen','mecagoenton',
    'jodercrist','jodercristo',
    'putojudas','judaputa',
    'diosmio','santisima',
    'sagradoculero',

    // ── ESPAÑOL: MAS INSULTOS DE CARACTER ─────────────────────────────────────
    'cabrón','cabrona',
    'gentuza','gentuzas',
    'chusma','chusmas',
    'escoria','escorias',
    'hez','heces',
    'basura','basuras',
    'inmundicia','inmundicias',
    'porquería','porquerías',
    'mugre','mugres',
    'suciedad','suciedades',
    'inmundo','inmunda',
    'mugriento','mugrienta',
    'roñoso','roñosa','roñosos','roñosas',
    'asqueroso','asquerosa',
    'repugnante','repugnantes',
    'nauseabundo','nauseabunda',
    'repulsivo','repulsiva',
    'odioso','odiosa','odiosos','odiosas',
    'detestable','detestables',
    'aborrecible','aborrecibles',
    'abominable','abominables',
    'execrable','execrables',
    'infame','infames','infamia','infamias',
    'deshonra','deshonras',
    'vergüenza','vergüenzas',
    'oprobio','oprobios',
    'ignominia','ignominias',
    'vileza','vilezas',
    'bajeza','bajezas',
    'maldad','maldades',
    'perversidad','perversidades',
    'perfidia','perfidias',
    'falsedad','falsedades',
    'doblez','dobleces',
    'hipocresía','hipocresías',
    'traición','traiciones',
    'felonía','felonías',
    'alevosía','alevosías',
    'villanía','villanías',

    // ── ESPAÑOL: INSULTOS CON SUFIJO -AZO ────────────────────────────────────
    'idiotazo','idiotaza','idiotazos','idiotazas',
    'imbecilazos','imbecilazo','imbecilazotas',
    'estupidazo','estupidaza',
    'taradazo','taradaza','taradazos','taradazas',
    'burrazo','burraza','burrazos','burrazas',
    'babosazo','babosaza','babosazos','babosazas',
    'pendejazote','pendejazota',
    'cabronazo','cabronaza',
    'putazo','putaza',
    'culero','culerazo','culerazo',
    'vergajazo','vergajaza',

    // ── ESPAÑOL: INSULTOS CON SUFIJO -ÍSIMO ──────────────────────────────────
    'idiotísimo','idiotísima','idiotísimos','idiotísimas',
    'estupidísimo','estupidísima',
    'imbecilísimo','imbecilísima',
    'taradísimo','taradísima',
    'burrisimo','burrisima',
    'baborísimo','babosísima',
    'tonterisima','tonterisimo',
    'cobardísimo','cobardísima',
    'miserabilísimo','miserabilísima',
    'asquerosísimo','asquerosísima',
    'repugnantísimo','repugnantísima',
    'pendejonísimo','pendejonísima',
    'cabronísimo','cabronísima',
    'mierdísimo','mierdísima',
    'putísimo','putísima',

    // ── ESPAÑOL: INSULTOS CON PREFIJO RE- / RELE- ────────────────────────────
    'reidiota','reidiota',
    'reimbécil','reimbecil',
    'reestúpido','reestupida',
    'retarado','retarada',
    'reburro','reburra',
    'remierda',
    'reputa','reputas',
    'recabron','recabrona',
    'rependejo','rependeja',
    'reculero','reculera',
    'rechiflado','rechiflada',
    'reloco','reloca',

    // ── ESPAÑA: MAS INSULTOS REGIONALES ──────────────────────────────────────
    'jilipollas','jilipolla',
    'capullines','capullin',
    'hostiacaldero',
    'cojonero','cojonera','cojoneros','cojoneras',
    'cojonuda','cojonudo',
    'cojonazos',
    'vergaras','vergara',
    'puñetero','puñetera','puñeteros','puñeteras',
    'follaculo','follaculos',
    'pollastro','pollastrón',
    'cagalcal','cagón',
    'meapilas','meapila',
    'hijoputa','hijaputa',
    'coñazo','coñazos',
    'mamonazo','mamonaza',
    'gilipuertas','gilapuertas',
    'soplagaitas',
    'pedazo_de_bruto',
    'grandísimo_idiota',
    'pedazo_de_animal',

    // ── MEXICO: PALABRAS ADICIONALES ──────────────────────────────────────────
    'ojete','ojetes',
    'ojeton','ojetona','ojetones','ojetonas',
    'fresón','fresona','fresones','fresonas',
    'populacho',
    'plebe','plebes',
    'raza','razas',
    'chaviza',
    'vieja','viejas',
    'viejo','viejos',
    'carnala','carnales',
    'carnal','carnales',
    'cuatachos','cuatacho',
    'sangron','sangrona','sangrones','sangronas',
    'sangrón','sangrona',
    'envidioso','envidiosa',
    'chismoso','chismosa',
    'hocicon','hocicona',
    'bocón','bocona','bocones','boconas',
    'copeton','copetona',
    'borrachito','borrachita',
    'chingaquedito',
    'metiches','metiche',
    'palero','palera','paleros','paleras',
    'lambiscon','lambiscona','lambiscones','lambisconas',
    'lambiscon','lambiscona',
    'lisonjero','lisonjera',
    'adulador','aduladora',
    'arrastra','arrastrado','arrastrada','arrastradores',
    'arrastrado','arrastrada',

    // ── COLOMBIA: MAS INSULTOS ────────────────────────────────────────────────
    'parce','parces',
    'chimbada','chimbadas',
    'chimbo','chimba',
    'marica','maricas',
    'güevon','güevona',
    'pirobo','piroba',
    'gonorrea','gonorreas',
    'hijueputa',
    'hijueputas','hpta',
    'malparida','malparido',
    'berracos','berraca',
    'mondongo',
    'costalero',
    'carechimba','carechimbas',
    'carepicha','carepichas',
    'careverga','caremergas',
    'ñero','ñera','ñeros','ñeras',
    'parcero','parcera','parceros','parceras',
    'llave','llaves',
    'mosca','moscas',
    'sapo','sapa',
    'cagada','cagadas',
    'maldita','maldito',
    'pichurria','pichurrias',
    'pichar','picho','picha',
    'culicagado','culicagada',

    // ── ARGENTINA: MAS INSULTOS ───────────────────────────────────────────────
    'boludaz','boludas',
    'pelotudaz','pelotudas',
    'hdputa','hdspm',
    'ndeapc','ndlg',
    'conchadetumare',
    'turro','turra',
    'garca','garcas',
    'cheto','cheta','chetos','chetas',
    'careta','caretas',
    'falopero','falopera','faloperos','faloperas',
    'tranza','tranzas',
    'chabón','chabona',
    'villero','villera',
    'croata','croatas',
    'trucho','trucha','truchos','truchas',
    'firulete','firuletear',
    'cague','cagón',
    'colado','colada','colados','coladas',
    'sobrador','sobradora',
    'agrandado','agrandada',
    'pajero','pajera',
    'paquete','paquetes',
    'batata','batatas',
    'zanahoria','zanahorias',
    'boludasso','boludassa',
    'pelotasso','pelotassa',

    // ── CHILE: MAS INSULTOS ───────────────────────────────────────────────────
    'huevón','huevona',
    'conchetumadre','conchetumare',
    'culiado','culiada',
    'pije','pijes',
    'facho','facha','fachos','fachas',
    'flaite','flaites',
    'cuma','cumas',
    'ñuñoino','ñuñoina',
    'choro','chora','choros','choras',
    'choripiojo',
    'picante','picantes',
    'gil','gila',
    'sapo','sapa',
    'aweonao','aweonada',
    'weon','wena',
    'lacra','lacras',

    // ── VENEZUELA: MAS INSULTOS ───────────────────────────────────────────────
    'lambucio','lambucia','lambuciones','lambuciotas',
    'arrecho','arrecha',
    'jeva','jevas',
    'chamo','chama',
    'pana','panas',
    'vergatiaro','vergataria',
    'guevón','guevona',
    'pajúo','pajua',
    'conoetumadre',
    'mamagüevo','mamagüevos',
    'piojo','piojos',
    'lacho','lacha','lachos','lachas',
    'nojoda',
    'maldita_sea',
    'perra','perras',

    // ── INSULTOS CON ANIMALES (AMPLIADO) ──────────────────────────────────────
    'cerda','cerdas',
    'puerca','puercas',
    'chancha','chanchas',
    'marrana','marranas',
    'cochina','cochinas',
    'guarra','guarras',
    'perra','perras',
    'zorronas','zorrona',
    'furcia','furcias',
    'golfa','golfas',
    'ramera','rameras',
    'pendona','pendonas',
    'lagarta','lagartas',
    'arpía','arpías',
    'bruja','brujas',
    'brujona','brujonas',
    'lechona','lechonas',
    'becerra','becerrras',
    'cabra','cabras',
    'cochinazo','cochinaza',
    'puerqueza',
    'bestia',
    'animal','animales',
    'salvaje','salvajes',
    'mono','mona','monos','monas',
    'mandril','mandriles',
    'gorila','gorilas',
    'chimpancé','chimpances',
    'orangután','orangutanes',
    'babuino','babuinos',
    'gusano','gusanos',
    'lombriz','lombrices',
    'larva','larvas',
    'cucaracha','cucarachas',
    'escarabajo','escarabajos',
    'parásito','parásitos',
    'sanguijuela','sanguijuelas',
    'garrapata','garrapatas',
    'piojo','piojos',
    'pulga','pulgas',
    'chinche','chinches',
    'ladilla','ladillas',
    'sabandija','sabandijas',
    'alimaña','alimañas',

    // ── INSULTOS COMPUESTOS CREATIVOS ─────────────────────────────────────────
    'caradeverga','carasucia',
    'carabicho','carapicha',
    'caraguey','caragüey',
    'carahuevo','carachucha',
    'caracanalla','caracagada',
    'orejadevaca',
    'narizdeperro',
    'pelodemona',
    'pelodechimp',
    'bocadeserrote',
    'bocadecloaca',
    'bocademierda','bocademierdas',
    'alentodecloaca',
    'piedeburro',
    'cabezadeburro','cabezadeaño','cabezadeculo',
    'culodepollo',
    'culodegallina',
    'pescuezo',
    'tripas',
    'entripado',
    'tripaseco',

    // ── INSULTOS SEXUALES COMPUESTOS ──────────────────────────────────────────
    'comehuevos','comepinga',
    'comechucha','comecoño',
    'chupahuevos','chupapito',
    'mamapinga','mamaverga',
    'mamacoño','mamachucha',
    'lameculos','lamehuevos',
    'culisucio','culisucia',
    'pichosucio','pichasucia',
    'chupavergas','mamahuevos',

    // ── ENGLISH: COMPOUND INSULTS ─────────────────────────────────────────────
    'cockmonger','cockweasel','cockwomble','cockwaffle',
    'bellpiece','knobpiece','bellknob',
    'fuckwagon','fucktrumpet','fuckwhistle',
    'shitgibbon','shitbiscuit','shitcanoe',
    'assclap','assnoodle','assgoblin',
    'dicknoodle','dickwhistle','dickwagon',
    'bitchwagon','bitchnoodle','bitchface',
    'cuntwaffle','cuntcanoe','cuntnugget',
    'bastardface','bastardseed',
    'turdwhistle','turdnugget','turdblossom',
    'jerkwaffle','jerkwagon','jerkstick',
    'dillweed','dillhole','dillwad',
    'dipweed','dipwad','diphole',
    'shitbrick','shitcanoe','shitpickle',
    'fartface','fartnugget','fartwaffle',
    'scroteweasel','scrotelick','scroteface',
    'ballsack','ballbag','ballface',
    'toerag','toerags',
    'meatwhistle','meatwagon',
    'pissflap','pissflaps',
    'pissweasel','pisswhistle',
    'ratfucker','ratfuckers','ratfucking',
    'snot_for_brains',
    'used_tampon',

    // ── ENGLISH: DEROGATORY BODY TERMS ────────────────────────────────────────
    'lardass','lardasses',
    'fatass','fatasses',
    'fatso','fatsos',
    'tubs','tubby','tubbies',
    'pudgy','podge','podges',
    'porker','porkers',
    'heifer','heifers',
    'beefcake',
    'boneface','bonebag',
    'skeletor',
    'beak_face','bignose',
    'dumbo','dumbos',
    'ugly_mug',
    'crater_face',
    'pizza_face',
    'bucktooth','buckteeth',
    'snaggletooth','snaggletoothed',
    'butterface','butterfaces',
    'uggo','uggos',
    'munter','munters',
    'trollface','trollfaces',

    // ── ENGLISH: HOMOPHOBIC / TRANSPHOBIC (SLURS) ─────────────────────────────
    'faggot','fag','faggy','fagot','fagots',
    'dyke','dike','dike',
    'tranny','trannie','trannies',
    'shemale','shemales',
    'ladyboy','ladyboys',
    'hermaphrodite',
    'queer','queers',
    'pansy','pansies',
    'nancy','nancies',
    'fairy','fairies',
    'poofter','poofters',
    'poof','poofs',
    'batty_boy','batty_man',
    'bender','benders',
    'limp_wrist',
    'fruit','fruity',

    // ── ENGLISH: STALKER / ABUSE TERMS ───────────────────────────────────────
    'stalker','stalkers','stalking',
    'creep','creeps','creepy',
    'perverted','perv',
    'predator','predators',
    'groomer','groomers',
    'pedophile','pedophiles','pedo','pedos',
    'kiddie_fiddler','kid_toucher',
    'molester','molesters',
    'rapist','rapists',
    'abuser','abusers',

    // ── ENGLISH: RELIGIOUS/RACIST CURSES ─────────────────────────────────────
    'godforsaken','goddamned','godless',
    'hellspawn','hell_spawn',
    'devil_spawn','demon_spawn',
    'satan_spawn','satanic',
    'antichrist',

    // ── ENGLISH: SLANG FOR GENITALS ──────────────────────────────────────────
    'schlong','schlongs',
    'shlong','shlongs',
    'wang','wangs',
    'dong','dongs',
    'dingdong','dingdongs',
    'johnson','johnsons',
    'todger','todgers',
    'willy','willies',
    'weenie','weenies',
    'willie','willies',
    'privates',
    'member','members',
    'stiffy','stiffies',
    'boner','boners',
    'hard_on','hardons',
    'wood','woods',
    'rod','rods',
    'shaft','shafts',
    'tool','tools',
    'weapon','weapons',
    'meat','meats',
    'snatch','snatches',
    'muffin','muffins',
    'clam','clams',
    'box','boxes',
    'honey_pot',
    'love_canal',
    'minge','minges',
    'fanny','fannies',
    'gash','gashes',
    'cooter','cooters',
    'beaver','beavers',
    'cooch','cooches',
    'vajayjay',
    'punani','punany','punanies',

    // ── ENGLISH: SEX ACTS AS INSULTS ─────────────────────────────────────────
    'blowjob','blowjobs',
    'handjob','handjobs',
    'rimjob','rimjobs',
    'rim_job',
    'reach_around',
    'teabag','teabagged','teabagging',
    'motorboat','motorboating',
    'titjob','tit_job',
    'cockblock','cockblocking','cockblocked',
    'jerk_off','jerking_off',
    'jack_off','jacking_off',
    'beat_off','beating_off',
    'cum','cumshot','cumshots',
    'cum_bucket','cum_dumpster',
    'cum_rag','cum_stain',
    'creampie','creampied',
    'gangbang','gangbanged','gangbanging',
    'orgy','orgies',
    'bukakke','bukake',
    'deepthroat','deepthroating',
    'facefuck','facefucking',
    'facials','facial',
    'fisting','fist_fuck',
    'scat','shitplay',
    'felching','felch',

    // ── ENGLISH: INTERNET MEMES / NEWER SLANG ─────────────────────────────────
    'ratio','ratioed',
    'owned','pwned','pwnt',
    'rekt','wrecked','destroyed',
    'rip','get_rekt',
    'loser_alert',
    'get_dunked',
    'yikes',
    'cringe_worthy','super_cringe',
    'cope','seething',
    'mald','malding',
    'seethe','seethed',
    'touched_grass',
    'no_bitches',
    'virgin_detected',
    'small_pp',
    'have_sex',
    'go_outside',
    'touch_grass',
    'ok_zoomer',
    'ok_millennial',
    'based_and_cringe',
    'normie','normies',
    'faggoot',
    'r_word',
    'k_word',
    'n_word',

    // ── MISCELLANEOUS ENGLISH PROFANITY ───────────────────────────────────────
    'goddammit','goddamit',
    'holy_shit','holy_fuck','holy_crap',
    'what_the_fuck','what_the_shit',
    'what_the_hell','what_the_crap',
    'for_fucks_sake','for_petes_sake',
    'jesus_christ','jesus_fucking_christ',
    'christ_almighty','christ_on_a_cracker',
    'son_of_a_bitch','son_of_a_whore',
    'motherfucking','motherfucked',
    'cocksucker','cocksucking',
    'dicksucker','dicksucking',
    'ball_licker','ball_sack',
    'taint','taints',
    'gooch','gooches',
    'taint_muncher',
    'cum_guzzler','cum_guzzling',
    'sperm_burper',
    'jizz','jizzed','jizzing',
    'jizz_rag','jizz_sock',
    'skeet','skeeting',
    'nut','nutted','nutting',
    'bust_a_nut','busting_a_nut',
    'load','blow_a_load',
    'spunk','spunked',
    'spooge','spooged',
    'love_juice',
    'spluge','spluged',

    // ── ESPAÑOL: TERMINOS SEXUALES ADICIONALES ────────────────────────────────
    'encamarse','encamado','encamada',
    'revolcarse','revolcada','revolcado',
    'acostarse','acostado','acostada',
    'meterse','metido','metida',
    'darsela','darselo','darselas',
    'hacerlo','hacerla','hacerla',
    'hacerse','haciendola','haciendolo',
    'tirarsela','tirandosela',
    'clavarsela','clavarla','clavado','clavada',
    'meteresela','metersela','meterselo',
    'empotrar','empotrando','empotrado','empotrada',
    'penetrar','penetrando','penetrado','penetrada',
    'clavar','clavando','clavado','clavada',
    'tirar','tirando','tirado','tirada',
    'tromar','tromarse',
    'encular','enculando','enculado','enculada',
    'sodomizar','sodomizando','sodomizado','sodomizada',
    'violar','violando','violado','violada',

    // ── ESPAÑOL: GROSERÍAS EUFEMISMOS COMUNES ─────────────────────────────────
    'maldita','maldito','malditas','malditos',
    'mecachis','ostras','ostia',
    'hostia','hostias',
    'rediós','redios',
    'leches','leche',
    'narices','nariz',
    'monadas','monada',
    'coñes','coñe',
    'puñeta','puñetas',
    'jopé','jope',
    'córcholis','corcholís',
    'cáspita','caspita',
    'recórcholis',
    'recristena',
    'rechifla','rechiflar',
    'arrejuntarse',

    // ── ESPAÑOL: TÉRMINOS PEYORATIVOS CLASISTAS ───────────────────────────────
    'muerto_de_hambre',
    'pobretón','pobretona',
    'miserable','miserables',
    'mendigo','mendiga','mendigos','mendigas',
    'limosnero','limosnera',
    'vagabundo','vagabunda',
    'vago','vaga','vagos','vagas',
    'holgazán','holgazana',
    'perezoso','perezosa',
    'flojo','floja','flojos','flojas',
    'parásito','parásita',
    'zángano','zángana',
    'mantenido','mantenida',
    'vividor','vividora',
    'gorrón','gorrona',
    'aprovechado','aprovechada',
    'oportunista','oportunistas',
    'trepador','trepadora',
    'rastrero','rastrera',

    // ── ESPAÑOL: FRASES HECHAS MALSONANTES ───────────────────────────────────
    'quetecalles','callatelaputa','callatelapinche',
    'metetelodonde','metetelotodo',
    'pudrete','pudreteymuere',
    'muertodehambre','muertodemiedo',
    'grandisimocabron','grandisimaputa',
    'reputisimamadre','tuputisimamadre',
    'mevaleverga','mevalelamierda',
    'mevaleuncarajo','mevaleuncacahuate',
    'vetealaverga','vetealachingada',
    'notemetas','notemetasdonde',
    'cometelo','cometela','cometelosobres',
    'meteteloporelculo','ponteloporelculo',

    // ── FRASES MULTIPLES ─────────────────────────────────────────────────────
    // ── VERBO PUTEAR: TIEMPOS FALTANTES ──────────────────────────────────────
    'puteo','puteas','putean','puteamos','puteais',
    'putee','puteaste','putearon',
    'puteaba','puteabas','puteabamos','puteaban',
    'puteare','putearas','putearan',

    // ── MAS CONJUGACIONES: VERBO CAGARLA ──────────────────────────────────────
    'cagarlo','cagarla','cagarlos','cagarlas',
    'lacagaste','lecagaste','mecague','secago',
    'lacago','lacagamos','lacagan','lacagaron',

    // ── MAS CONJUGACIONES: VERBO JODERLA ──────────────────────────────────────
    'joderla','joderlo','joderlas','joderlos',
    'lajodiste','selajodiste','lajodio','lajodemos',
    'lajodieron','lajodian','lajodere',

    // ── MAS CONJUGACIONES: VERBO CHINGÁRSELA ─────────────────────────────────
    'chingarla','chingarlas','chingarlos','chingarlosatodos',
    'lachingaste','selajodiste','lachingo','lachingaron',
    'lachingan','lachingamos',

    // ── ESPAÑOL: VARIANTES ORTOGRAFICAS ──────────────────────────────────────
    'cabrón','cabróna','cabronazo',
    'maricón','maricóna',
    'jodón','jodóna','jodonona',
    'tragón','tragóna',
    'comilón','comilóna',
    'mentirón','mentirona',
    'chillón','chillóna',
    'llorón','lloróna',
    'berrinchudo','berrinchuda',
    'tragapiedras','tragaflores',
    'tragonzote','tragonzota',
    'comeperros','comegatos','comecabras',

    // ── ESPAÑOL: HIPOCORÍSTICOS GROTESCOS ────────────────────────────────────
    'putita','putito',
    'jotito','jotita',
    'pendejtio','pendejita',
    'cabronzuelo','cabronzuela',
    'cochinillo','cochinilla',
    'burrito','burrita',
    'taradito','taradita',
    'bobito','bobita',
    'tontonin','tontonina',
    'imbecilito','imbecilita',
    'vergajote','vergajota',
    'carculote','carculota',
    'mamoncito','mamoncita',
    'chingoncito','chingoncita',
    'perritazo','perritaza',

    // ── ESPAÑA: PALABROTAS HISTÓRICAS ─────────────────────────────────────────
    'leñe','leñes',
    'arrea','arreas',
    'caramba','carambas',
    'caracoles','caracol',
    'hala','halas',
    'jolín','jolines',
    'jopé','jolines',
    'recórcholis',
    'cáspita','córcholis',
    'caray','carays',
    'canastos','canasto',
    'demonio','demonios',
    'diablos','diablo',
    'infiernos','infierno',
    'maldición','maldiciones',
    'condenado','condenada',
    'maldito','maldita',
    'endiablado','endiablada',
    'endemoniad','endemoniada',

    // ── PALABRAS MALSONANTES TECNICAS ─────────────────────────────────────────
    'sodomía','sodomías',
    'bestialismo','zoofilia',
    'necrofilia','necrófilo','necrofila',
    'pedofilia','pederastia',
    'pederasta','pedófilo','pedofila',
    'voyerista','voyeurismo',
    'exhibicionismo','exhibicionista',
    'sadomasoquismo','masoca',
    'fetichista','fetiches',
    'ninfomania','ninfomana',
    'satiriasis','satiriaco',
    'pornógrafo','pornografa',
    'proxeneta','proxenetas',
    'alcahuete','alcahueta','alcahuetes','alcahuetas',
    'chulo','chula','chulos','chulas',
    'macarro','macarra',
    'vividor','vividora',
    'rufián','rufiana',

    // ── ENGLISH: MORE BODY INSULTS ────────────────────────────────────────────
    'ugly_cow','stupid_cow',
    'dumb_bitch','dumb_hoe',
    'fat_cunt','dumb_cunt',
    'stupid_bitch','crazy_bitch',
    'basic_bitch','thirsty_hoe',
    'dusty_hoe','ratchet_hoe',
    'ghetto_ass','ratchet_ass',
    'fugly','fugly_ass',
    'fug_face','ugly_face',
    'fug_life','fuglife',
    'pigface','pig_face',
    'horse_face','dog_face',
    'rat_face','cat_face',
    'crater_face','pizza_face',
    'pepperoni_face',

    // ── ENGLISH: SOCIAL MEDIA SPECIFIC ───────────────────────────────────────
    'clout_chaser','clout_chasing',
    'attention_whore','attention_seeker',
    'fake_ass','fake_bitch',
    'fake_friend','two_faced',
    'thirsty_ass','thirsty_bitch',
    'hoe_ass','broke_ass',
    'lame_ass','dusty_ass',
    'basic_ass','dumb_ass',
    'ugly_ass','stupid_ass',
    'racist_ass','sexist_ass',
    'triggered_snowflake',
    'triggered_little',
    'keyboard_warrior',
    'internet_tough_guy',
    'basement_dweller',
    'neckbeard_virgin',
    'forever_alone',
    'no_life','no_friends',
    'virgin_forever',
    'die_alone',

    // ── ENGLISH: GAMING INSULTS ───────────────────────────────────────────────
    'noob','n00b','noobie',
    'scrub','scrubs',
    'trash_player','trash_tier',
    'bot','bots',
    'cheater','cheaters','cheating',
    'hacker','hackers','hacking',
    'camper','campers','camping',
    'tryhard','tryhards',
    'sweatlord','sweat_lord',
    'git_rekt','git_good',
    'get_wrecked','get_rekt',
    'uninstall','get_uninstalled',
    'ez','ez_game','easy_game',
    'ez_clap','ez_wins',
    'ratio_plus_l',
    'fell_off','fallen_off',
    'mid','midder','middie',
    'dogwater','absolute_dogwater',
    'hardstuck','bronze','wood',
    'elo_hell','elo_hell_player',
    'one_trick','tunnel_vision',
    'afk','afker',
    'feeder','feeders','feeding',
    'inter','inting','inted',
    'troll','trolling',
    'griefing','griefer',

    // ── ENGLISH: MODERN SLANG INSULTS ────────────────────────────────────────
    'sus','super_sus',
    'bozo','bozos',
    'clown','clowning',
    'goofball','goofy_ahh',
    'ratio','ratioed','big_ratio',
    'cope_harder','copium',
    'malding',
    'seething','seethe',
    'rent_free',
    'L_take','bad_take','hot_take',
    'certified_clown','certified_bozo',
    'down_bad','down_horrendous',
    'caught_in_4k',
    'absolute_clown',
    'walking_L',
    'permanent_L',
    'skill_issue',
    'touch_grass_bro',
    'go_outside',
    'no_thoughts',
    'brain_empty',
    'room_temperature_iq',
    'negative_iq',
    'braindead','brain_dead',
    'mouth_breather',
    'knuckle_dragger',

    // ── ENGLISH: BODY FUNCTION INSULTS ───────────────────────────────────────
    'fart_face','fartbreath',
    'shit_breath','shit_stain',
    'piss_ant','piss_head',
    'cum_breath','cum_stained',
    'jizz_face','jizz_breath',
    'spunk_bubble','spunk_breath',
    'turd_burglar','turd_blossom',
    'poop_face','poop_breath',
    'stinky_ass','smelly_ass',
    'skid_mark','skid_marks',
    'wet_fart','shart','sharted',
    'pissed_pants','shit_pants',
    'diaper_filler',

    // ── ENGLISH: INTENSIFIERS (USED AS INSULTS) ───────────────────────────────
    'utter_trash','complete_trash',
    'absolute_moron','utter_moron',
    'massive_dickhead','giant_asshole',
    'supreme_idiot','colossal_idiot',
    'grade_a_asshole','grade_a_moron',
    'world_class_idiot','legendary_idiot',
    'professional_idiot','full_time_idiot',
    'olympic_level_stupid',
    'weapons_grade_stupid',
    'certified_moron','certified_idiot',

    // ── INGLES: GROSERÍAS CLASICAS ADICIONALES ────────────────────────────────
    'piss','pisser','pissed',
    'piss_off','pissing',
    'hell','hellhole',
    'damn','damnation',
    'blast','blasted','blasting',
    'cuss','cussing','cussed',
    'swear','swearing','swore',
    'filthy','filthier','filthiest',
    'dirty','dirtier','dirtiest',
    'foul','fouler','foulest',
    'disgusting','disgustingly',
    'vile','vilest',
    'putrid','putridness',
    'rotten','rottenness',
    'fetid','stinking','stank',
    'rank','rankness',
    'nasty','nastiest',
    'gross','grosser','grossest',
    'vomit','puke','puking',
    'puke_worthy',

    // ── ESPAÑOL: PALABRAS DE RELLENO MALSONANTES ──────────────────────────────
    'quedemala','quelosparida','quelopario',
    'quedemierdas','quelosengendra',
    'quelapario','quelamamada',
    'quelosengendro','quelostrajo',
    'andateporahi','andatealcarajo',
    'itealaverga','vetealaverga',
    'itealachingada',
    'mandatealcarajo','mandatealamierda',
    'mandatealavergota',
    'metetelaporelculo','metetelotodo',

    // ── MÉXICO: EUFEMISMOS MALSONANTES ────────────────────────────────────────
    'chispas','chispan',
    'carachas','carache',
    'tripas','tripear',
    'trueno','truenos',
    'muéndez','muendez',
    'fregado','fregada',
    'jijo','jija','jijos','jijas',
    'jijodela','jijodelas',
    'friega','friegas',
    'friegas','friegan',
    'chinguen','chingale',
    'chingao','chingados',
    'metiche','metiches',
    'lambiscon','lambiscona',

    // ── ESPAÑOL: GROSERÍAS POR CONTEXTO ESPECÍFICO ───────────────────────────
    // trabajo / jefe
    'pinchejefe','pinchejefa',
    'pendejojefe','culero_jefe',
    'mamonsote_jefe',
    // política
    'raterogobierno','rateropolítico',
    'corrupto_gobierno',
    'ladrón_político',
    // familia
    'malparidofamilia','putofamilia',
    'cabrónfamiliar',
    // escuela
    'culeropinche_maestro','pincheprofesor',
    // tráfico
    'cretinomaneja','idiotamaneja',
    'burrodemanejando',

    // ── FRASES MULTIPLES EN ESPAÑOL ──────────────────────────────────────────
    'vete a la chingada',
    'chinga tu madre',
    'que te jodan',
    'vete a la mierda',
    'me vale madres',
    'vete al carajo',
    'hijo de puta',
    'hija de puta',
    'hijo de la chingada',
    'me cago en tu madre',
    'puta madre',
    'a la verga',
    'a la chingada',
    'chingatu madre',
    'hijo de su puta madre',
    'me vale verga',
    'no me chingues',
    'chinga tu puta madre',
    'pinche pendejo',
    'pinche cabron',
    'pinche culero',
    'pinche idiota',
    'vete a la verga',
    'la concha de tu madre',
    'andate a la puta',
    'que te folle un pez',
    'hijo de la gran puta',
    'me cago en dios',
    'me cago en la leche',
    'me cago en todo',
    'que se joda',
    'que te jodan',
    'a tomar por culo',
    'a tomar por saco',
    'vete a tomar por culo',
    'anda a cagar',
    'anda a la puta',
    'anda a la mierda',
    'te vas a la puta',
    'te mando a la mierda',
    'que te den',
    'que te den por culo',
    'vete a la mierda',
    'chupame el bicho',
    'chupame la verga',
    'lameme el culo',
    'besame el culo',
    'chupame un huevo',
    'metete eso donde te quepa',
    'ponme aqui la firma',
    'me la pelan',
    'me la suda',
    'me cae gordo',
    'que se vaya a la chingada',
    'hijo de su pinche madre',
    'vieja puta',
    'viejo pendejo',
    'vieja culera',
    'pinche vieja',
    'pinche viejo',
    'que le den',
    'que se chingue',
    'chinguen a su madre',
    'se me para',
    'voy a agarrarte a chingadazos',
    'te voy a partir la cara',
    'te voy a romper el hocico',

    // ── FRASES MULTIPLES EN INGLES ────────────────────────────────────────────
    'go to hell',
    'go fuck yourself',
    'fuck you',
    'fuck off',
    'kiss my ass',
    'eat shit',
    'suck my dick',
    'suck my cock',
    'eat a dick',
    'son of a bitch',
    'piece of shit',
    'what the fuck',
    'holy shit',
    'holy fuck',
    'for fucks sake',
    'shut the fuck up',
    'get the fuck out',
    'you piece of shit',
    'jesus fucking christ',
    'drop dead',
    'eat a bag of dicks',
    'shove it up your ass',
    'stick it where the sun dont shine',
    'go to hell and stay there',
    'get bent',
    'screw you',
    'screw off',
    'piss off',
    'piss on you',
    'go screw yourself',
    'you stupid bastard',
    'you dumb fuck',
    'you fucking moron',
    'you fucking idiot',
    'you dumb bitch',
    'stupid motherfucker',
    'dumb motherfucker',
    'you piece of garbage',
    'you worthless piece of shit',
    'you absolute moron',
    'you complete idiot',
    'kiss my ass goodbye',
    'bite me',
    'bite my ass',
    'lick my ass',
    'lick my balls',
    'blow me',
    'choke on it',
    'choke on a dick',
    'fuck right off',
    'fuck all the way off',
    'get fucked',
    'get fucked up',
    'suck my balls',
    'eat my ass',
    'i hope you choke',
    'i hope you die',
    'rot in hell',
    'burn in hell',
    'go to hell and rot',
    'you can go fuck yourself',
    'go fuck a cactus',
    'fuck a duck',
    'fuck yourself sideways',
    'take a long walk off a short pier',
    'shove it',
    'shove it up your ass',
    'shove it where the sun dont shine',
    'you stupid twat',
    'you dumb cunt',
    'you little shit',
    'you little bitch',
    'you little bastard',
  };

  static String _normalizar(String texto) {
    const reemplazos = {
      'á': 'a', 'à': 'a', 'ä': 'a', 'â': 'a',
      'é': 'e', 'è': 'e', 'ë': 'e', 'ê': 'e',
      'í': 'i', 'ì': 'i', 'ï': 'i', 'î': 'i',
      'ó': 'o', 'ò': 'o', 'ö': 'o', 'ô': 'o',
      'ú': 'u', 'ù': 'u', 'ü': 'u', 'û': 'u',
      'ñ': 'n',
      '@': 'a',
      '4': 'a',
      '3': 'e',
      '1': 'i',
      '!': 'i',
      '0': 'o',
      r'$': 's',
      '5': 's',
      '7': 't',
    };
    var resultado = texto.toLowerCase();
    reemplazos.forEach((original, reemplazo) {
      resultado = resultado.replaceAll(original, reemplazo);
    });
    return resultado;
  }

  static bool contiene(String texto) {
    final normalizado = _normalizar(texto).trim();
    final tokens = normalizado.split(RegExp(r'\s+'));
    for (final token in tokens) {
      final palabra = token.replaceAll(RegExp(r'[^a-z]'), '');
      if (palabra.isNotEmpty && _palabras.contains(palabra)) return true;
    }
    for (final frase in _palabras) {
      if (frase.contains(' ') && normalizado.contains(frase)) return true;
    }
    return false;
  }

  static String censurar(String texto) {
    return texto.splitMapJoin(
      RegExp(r'\S+'),
      onMatch: (m) {
        final token = m[0]!;
        final palabra =
            _normalizar(token).replaceAll(RegExp(r'[^a-z]'), '');
        if (palabra.isNotEmpty && _palabras.contains(palabra)) {
          return '*' * token.length;
        }
        return token;
      },
      onNonMatch: (s) => s,
    );
  }
}
